export const REQUEST_ROUTE = 'REQUEST_ROUTE'
export const RECEIVE_ROUTE_SUCCESS = 'RECEIVE_ROUTE_SUCCESS'
export const RECEIVE_ROUTE_FAILURE = 'RECEIVE_ROUTE_FAILURE'
export const SELECT_TOURER = 'SELECT_TOURER'

